-- Nettoyage préalable (ordre important pour Oracle)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ASSEMBLER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMPOSANT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PIECE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ASSEMBLAGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TYPE ListeQualiteT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TYPE IndiceQualiteT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TYPE EquipeT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TYPE MembreEquipeT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Définition des types objets
CREATE OR REPLACE TYPE MembreEquipeT AS OBJECT (
  Nom VARCHAR2(50),
  Fonction VARCHAR2(50)
);
/
CREATE OR REPLACE TYPE EquipeT AS TABLE OF MembreEquipeT;
/
CREATE OR REPLACE TYPE IndiceQualiteT AS OBJECT (
  TypeIndice VARCHAR2(50),
  PoidsActuel NUMBER,
  Valeur NUMBER
);
/
CREATE OR REPLACE TYPE ListeQualiteT AS VARRAY(10) OF IndiceQualiteT;
/

-- Table ASSEMBLAGE (entité de base)
CREATE TABLE ASSEMBLAGE (
  id_assemblage NUMBER PRIMARY KEY,
  nom VARCHAR2(255) NOT NULL
);

-- Table COMPOSANT
CREATE TABLE COMPOSANT (
  nomC VARCHAR2(100),
  id_composant NUMBER PRIMARY KEY,
  prix_unitaire NUMBER(10, 2) NOT NULL,
  FOREIGN KEY (id_composant) REFERENCES ASSEMBLAGE(id_assemblage)
);

-- Table ASSEMBLER
CREATE TABLE ASSEMBLER (
  idA NUMBER NOT NULL,
  id_isA NUMBER NOT NULL,
  quantite NUMBER NOT NULL CHECK (quantite > 0),
  PRIMARY KEY (idA, id_isA),
  FOREIGN KEY (idA) REFERENCES ASSEMBLAGE(id_assemblage),
  FOREIGN KEY (id_isA) REFERENCES ASSEMBLAGE(id_assemblage)
);

-- Table PIECE
CREATE TABLE PIECE (
  id_assemblage NUMBER PRIMARY KEY,
  DateDebut DATE,
  DateFin DATE,
  Equipe EquipeT,
  IndicesQualite ListeQualiteT,
  FOREIGN KEY (id_assemblage) REFERENCES ASSEMBLAGE(id_assemblage)
)
NESTED TABLE Equipe STORE AS Equipe_store;